apiVersion: v1
kind: ConfigMap
metadata:
  name: grafana-datasources
  namespace: connectcamp
data:
  datasources.yaml: |
    apiVersion: 1
    datasources:
      - name: Prometheus
        type: prometheus
        url: http://prometheus-service:9090
        access: proxy
        isDefault: true
        editable: false
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: grafana-dashboard-provider
  namespace: connectcamp
data:
  dashboards.yaml: |
    apiVersion: 1
    providers:
      - name: connectcamp-dashboards
        orgId: 1
        folder: ConnectCamp
        type: file
        disableDeletion: false
        editable: true
        options:
          path: /var/lib/grafana/dashboards
