apiVersion: v1
kind: ConfigMap
metadata:
  name: connectcamp-config
  namespace: connectcamp
data:
  SPRING_DATASOURCE_URL: "jdbc:mysql://mysql-service:3306/projet_integre?createDatabaseIfNotExist=true&useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true"
  SPRING_DATASOURCE_USERNAME: "root"
  SPRING_JPA_HIBERNATE_DDL_AUTO: "update"
  SPRING_JPA_SHOW_SQL: "false"
  SERVER_PORT: "8089"
  # Remplacer <INGRESS_IP> par l'IP réelle du nœud après déploiement
  CORS_ALLOWED_ORIGINS: "http://localhost:4200,http://localhost:3000"
  FRONTEND_URL: "http://localhost:4200"
  MAIL_USERNAME: "yaichfarah1@gmail.com"
  MYSQL_DATABASE: "projet_integre"
