apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
  namespace: connectcamp
  labels:
    app: backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/path: "/actuator/prometheus"
        prometheus.io/port: "8089"
    spec:
      initContainers:
        - name: wait-for-mysql
          image: busybox:1.36
          command: ['sh', '-c', 'until nc -z mysql-service 3306; do echo "Waiting for MySQL..."; sleep 2; done']
      containers:
        - name: backend
          # Remplacer <DOCKERHUB_USERNAME> par ton username Docker Hub
          image: farah893/connectcamp-backend:latest
          ports:
            - containerPort: 8089
          envFrom:
            - configMapRef:
                name: connectcamp-config
            - secretRef:
                name: connectcamp-secrets
          volumeMounts:
            - name: uploads-storage
              mountPath: /app/uploads
          resources:
            requests:
              memory: "256Mi"
              cpu: "100m"
            limits:
              memory: "512Mi"
              cpu: "300m"
      volumes:
        - name: uploads-storage
          persistentVolumeClaim:
            claimName: backend-uploads-pvc
