package tn.esprit.projetPi.entities;

public enum EmailType {
    WELCOME,
    EMAIL_VERIFICATION,
    PASSWORD_RESET,
    ORDER_CONFIRMATION,
    ORDER_SHIPPED,
    ORDER_DELIVERED,
    ORDER_CANCELLED,
    REFUND_APPROVED,
    REFUND_COMPLETED,
    REVIEW_REMINDER,
    STOCK_ALERT,
    PRICE_DROP_ALERT,
    PROMOTIONAL
}
